# Expose your documentation as JSON swagger compliant
app.api_documentation_json:
    path: /api/docs
    methods: GET
    defaults:
        _controller: nelmio_api_doc.controller.swagger
        _format: json

## Requires the Asset component and the Twig bundle
## $ composer require twig asset
app.api_documentation_ui:
    path: /api/docs-ui
    methods: GET
    defaults:
        _controller: nelmio_api_doc.controller.swagger_ui
