controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /api/login
    controller: App\Controller\AuthController::login
    methods: POST

app_logout:
    path: /api/logout
    controller: App\Controller\AuthController::logout
    methods: POST

app_api_add_sensor:
    path: /api/sensors
    controller: App\Controller\SensorController::createSensor
    methods: POST

app_api_list_sensors:
    path: /api/sensors
    controller: App\Controller\SensorController::listSensors
    methods: GET

app_api_list_wines:
    path: /api/wines/measurements
    controller: App\Controller\WineController::listWinesMeasurements
    methods: GET

app_api_add_measurements:
    path: /api/measurements
    controller: App\Controller\MeasurementController::createMeasurement
    methods: POST









